package proyecto_biblioteca.Vista;

public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        POD = new javax.swing.JComboBox<>();
        LibroNombre = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        PD = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextNameLibro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        POD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestamo", "Devolución" }));
        getContentPane().add(POD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, -1));

        LibroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroNombreActionPerformed(evt);
            }
        });
        getContentPane().add(LibroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 360, -1));

        BuscarButton.setText("Buscar");
        getContentPane().add(BuscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        PD.setText("Prestamo/Devolución");
        getContentPane().add(PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 290, -1));

        TextNameLibro.setText("Digite el nombre del libro");
        getContentPane().add(TextNameLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibroNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BuscarButton;
    private javax.swing.JLabel Fondo;
    public javax.swing.JTextField LibroNombre;
    private javax.swing.JLabel PD;
    public javax.swing.JComboBox<String> POD;
    private javax.swing.JLabel TextNameLibro;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
