package proyecto_biblioteca.Vista;

public class Devolver extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Devolver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        CodeLibro = new javax.swing.JTextField();
        AceptarButton = new javax.swing.JButton();
        CodeLibroTXT = new javax.swing.JLabel();
        CodeUser = new javax.swing.JTextField();
        TextCodUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CodeLibro.setBackground(new java.awt.Color(240, 240, 240));
        CodeLibro.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(CodeLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 20));

        AceptarButton.setText("Aceptar");
        getContentPane().add(AceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, 20));

        CodeLibroTXT.setText("Digite el código del libro");
        getContentPane().add(CodeLibroTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        CodeUser.setBackground(new java.awt.Color(240, 240, 240));
        CodeUser.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(CodeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 20));

        TextCodUser.setText("Digite el código del usuario");
        getContentPane().add(TextCodUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 30, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AceptarButton;
    public javax.swing.JTextField CodeLibro;
    private javax.swing.JLabel CodeLibroTXT;
    public javax.swing.JTextField CodeUser;
    private javax.swing.JLabel TextCodUser;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
