package proyecto_biblioteca.Vista;


public class Registro_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Prestar
     */
    public Registro_Estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserCode = new javax.swing.JTextField();
        TitleCodeLib = new javax.swing.JLabel();
        NombreUser = new javax.swing.JTextField();
        TextNameUser = new javax.swing.JLabel();
        EdadUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JLabel();
        Programa = new javax.swing.JTextField();
        InstitucEst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextPrograma = new javax.swing.JLabel();
        TextInstEst = new javax.swing.JLabel();
        AceptarBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserCode.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(UserCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 20));

        TitleCodeLib.setText("Código Usuario");
        getContentPane().add(TitleCodeLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        NombreUser.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(NombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 20));

        TextNameUser.setText("Nombre Del Solicitante");
        getContentPane().add(TextNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 20));

        EdadUser.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(EdadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 60, -1));

        jLabel1.setText("Edad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, -1));

        Telefono.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        TextTelefono.setText("Telefono");
        getContentPane().add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        Programa.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(Programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 150, -1));

        InstitucEst.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(InstitucEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Estudiante");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 140, 30));

        TextPrograma.setText("Programa / Grado");
        getContentPane().add(TextPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 140, -1));

        TextInstEst.setText("Institucion");
        getContentPane().add(TextInstEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, -1));

        AceptarBT.setText("Aceptar");
        getContentPane().add(AceptarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AceptarBT;
    public javax.swing.JTextField EdadUser;
    public javax.swing.JTextField InstitucEst;
    public javax.swing.JTextField NombreUser;
    public javax.swing.JTextField Programa;
    public javax.swing.JTextField Telefono;
    private javax.swing.JLabel TextInstEst;
    private javax.swing.JLabel TextNameUser;
    private javax.swing.JLabel TextPrograma;
    private javax.swing.JLabel TextTelefono;
    private javax.swing.JLabel TitleCodeLib;
    public javax.swing.JTextField UserCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
