package proyecto_biblioteca.Vista;


public class Registro_Ciudadano extends javax.swing.JFrame {

    /**
     * Creates new form Prestar
     */
    public Registro_Ciudadano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserCode = new javax.swing.JTextField();
        TitleCodeLib = new javax.swing.JLabel();
        NombreUser = new javax.swing.JTextField();
        TextNameUser = new javax.swing.JLabel();
        EdadUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextCity = new javax.swing.JLabel();
        TextDire = new javax.swing.JLabel();
        AceptarBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserCode.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(UserCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 20));

        TitleCodeLib.setText("Código Usuario");
        getContentPane().add(TitleCodeLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        NombreUser.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(NombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 20));

        TextNameUser.setText("Nombre Del Solicitante");
        getContentPane().add(TextNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 20));

        EdadUser.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(EdadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 60, -1));

        jLabel1.setText("Edad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, -1));

        Telefono.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        TextTelefono.setText("Telefono");
        getContentPane().add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        City.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 150, -1));

        Direccion.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ciudadano");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 140, 30));

        TextCity.setText("Ciudad");
        getContentPane().add(TextCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, -1));

        TextDire.setText("Direccion");
        getContentPane().add(TextDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 120, -1));

        AceptarBT.setText("Aceptar");
        getContentPane().add(AceptarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Ciudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Ciudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Ciudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Ciudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Ciudadano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AceptarBT;
    public javax.swing.JTextField City;
    public javax.swing.JTextField Direccion;
    public javax.swing.JTextField EdadUser;
    public javax.swing.JTextField NombreUser;
    public javax.swing.JTextField Telefono;
    private javax.swing.JLabel TextCity;
    private javax.swing.JLabel TextDire;
    private javax.swing.JLabel TextNameUser;
    private javax.swing.JLabel TextTelefono;
    private javax.swing.JLabel TitleCodeLib;
    public javax.swing.JTextField UserCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
